version: '2'
services:
  bank:
    image: 'bank:v1'
  cart:
    image: 'cart:v1'
  products:
    image: 'products:v1'
  purchase:
    image: 'purchase:v1'
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev
  backend-tests:
    image: 'backend-tests:v1'
    links:
      - cart:cart.dev
      - bank:bank.dev
      - products:products.dev
      - purchase:purchase.dev
  gateway:
    image: 'banking-gateway:v1'
    build:
      context: './banking_gateway'
    ports:
      - "8085:80"
    links:
      - products:products.dev
      - bank:bank.dev
  api-tests:
    image: 'banking-api-spec:v1'
    build:
      context: './spec/api-features'
    links:
      - gateway:gateway.dev
      - products:products.dev
      - cart:cart.dev
      - bank:bank.dev
      - purchase:purchase.dev
    volumes:
      - "./spec/api-features/spec:/usr/src/app/spec"
  frontend:
    image: 'banking-frontend:v1'
    ports:
      - "8080:80"
    links:
      - cart:cart.dev
      - gateway:gateway.dev
    build:
      context: '${FRONTEND_DIR}'
    volumes:
      - './${FRONTEND_DIR}/src/client:/usr/share/nginx/html'
